### ISSUE TITLE
can you add option to save the output to google drive directly 

### ISSUE THREAD

**Issue by VYRION-Ai** [sovit-123/fasterrcnn-pytorch-training-pipeline#92]
thank you for your great work,
when training on Collab( most of us do that )  the output saved in the Collab 
, please can you edit code to make the save to be the dir we  write in the  --name  , so it take it as it , if i choose the google drive it go directly to drive , because training takes a lot of time , and many times session closed before saving to drive and i have to stope training to copy the output to drive

**Comment by sovit-123** [comment]
@VYRION-Ai 
Thanks for the suggestion. However, there are a few issues with that. To save to Google Drive, you need to connect it first which asks for credentials. That cannot be done automatically. What I can do is add another argument that can take user path directly to save to a directory instead of `outputs` directory. But for that also, the user will have to connect to Google Drive first and then provide the custom directory path to the Drive.

I hope this makes sense. Let me know your thoughts.

**Comment by VYRION-Ai** [comment]
@sovit-123 yes connection is not done automatically. most of us load the dataset from google drive so we have to make connection ,  add new argument  will be great , the important thing is to save automatically to drive . thank you @sovit-123 , this will be great achievement to us and will save us a lot

**Comment by sovit-123** [comment]
Sure. I will try to push the update as soon as possible.

**Comment by sovit-123** [comment]
@VYRION-Ai 
Now, you can give path to any custom directory including Google Drive using `--project-dir` command. 
Example:
`python train.py --data data_configs/custom_data.yaml --epochs 2 --model fasterrcnn_resnet50_fpn_v2 --project-dir "/content/drive/MyDrive/Colab Notebooks/fasterrcnn_repository/custom_training" --batch 4`

Please pull the latest code.

**Comment by VYRION-Ai** [comment]
@sovit-123 thank you very much

**Comment by sovit-123** [comment]
Welcome.
